**1**. Play 5 rounds of [regex golf](https://alf.nu/RegexGolf)! The 5 rounds are

- Warmup
- Anchors
- It never ends
- Ranges
- Backrefs

Write the list of regular expressions used below. There may be several possible solutions - you only need one.

warmup - "foo"  
Anchors = ".*ck$"  
It never ends = "fu\b"  
Ranges = "^[a-f]{4}"  
Backrefs = "(.{3}).*\1"

**2**. Simulate 1000 flips of a fair coin, using 'H' for heads and 'T' for tails, and store the results as a string. Count the number of times at least 5 heads occur consecutively.

- Do this using a regex
- Do this without using a regex

In [3]:
import re
import random
random.seed(10)
flips = "".join([str(random.randint(0,1)) for x in range(1000)])
flips = flips.replace("1","H").replace("0","T")
# Using regex
print(len(re.findall("(?=HHHHH)",flips)))

# Without regex
count = 0
for i in range(len(flips)-5):
    if flips[i] != "H":
        continue
    else:
        if flips[i:i+5] == "HHHHH":
            count += 1
print(count)

38
38


**3**. Generate a random 3 $\times$ 4 matrix with entries from the digits 0-9. 

- Scale it so that all columns have mean zero and standard deviation 1
- Scale it so that all rows have minimum 0 and maximum 1

In [2]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

mat = np.random.randint(10,size=(3,4))
print(mat)
print("\n")
mat1 = StandardScaler().fit_transform(mat)
print(mat1)
print("\n")
mat2 = MinMaxScaler().fit_transform(mat.T).T
print(mat2)

[[9 5 7 5]
 [4 4 4 9]
 [4 4 9 7]]


[[ 1.41421356  1.41421356  0.16222142 -1.22474487]
 [-0.70710678 -0.70710678 -1.29777137  1.22474487]
 [-0.70710678 -0.70710678  1.13554995  0.        ]]


[[1.  0.  0.5 0. ]
 [0.  0.  0.  1. ]
 [0.  0.  1.  0.6]]


**4**. Create this matrix using `np.fromfunction` 

```
array([[18, 13, 10,  9, 10, 13, 18],
       [13,  8,  5,  4,  5,  8, 13],
       [10,  5,  2,  1,  2,  5, 10],
       [ 9,  4,  1,  0,  1,  4,  9],
       [10,  5,  2,  1,  2,  5, 10],
       [13,  8,  5,  4,  5,  8, 13],
       [18, 13, 10,  9, 10, 13, 18]])
```

In [3]:
nums = np.array([0,5,8,9,8,5,0])
np.fromfunction(lambda i,j: 18 - nums[j.astype(int)] - nums[i.astype(int)], (7,7))

array([[18, 13, 10,  9, 10, 13, 18],
       [13,  8,  5,  4,  5,  8, 13],
       [10,  5,  2,  1,  2,  5, 10],
       [ 9,  4,  1,  0,  1,  4,  9],
       [10,  5,  2,  1,  2,  5, 10],
       [13,  8,  5,  4,  5,  8, 13],
       [18, 13, 10,  9, 10, 13, 18]])

**5**. Write a function `make_df` that returns something like the output shown below when called with `make_df(12)`. Here the outcome is random with equal probability.

<img src="df.png" alt="Table" style="width: 200px;"/>

In [4]:
import pandas as pd
from itertools import cycle
def make_df(num):
    label_cycle = cycle(["A","B","C"])
    
    pids = ["S"+str(x).zfill(4) for x in range(num)]
    group = [next(label_cycle) for x in range(num)]
    outcome = random.choices(["died","survived"],k=num)
    
    return pd.DataFrame({"pids":pids,"group":group,"outcome":outcome})

In [5]:
make_df(12)

pids group   outcome
0   S0000     A      died
1   S0001     B  survived
2   S0002     C      died
3   S0003     A      died
4   S0004     B  survived
5   S0005     C      died
6   S0006     A      died
7   S0007     B  survived
8   S0008     C  survived
9   S0009     A  survived
10  S0010     B      died
11  S0011     C      died